apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-client
  template:
    metadata:
      labels:
        app: todo-client
    spec:
      containers:
      - name: todo-client
        image: mohammed102003/todo-client:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://todo-server-service:5001"
